Develop
Aziderius/bank pull request #4
Opened 2023-10-16 21:36 UTC by Aziderius

https://github.com/Aziderius/bank/issues/1

con este código se satisface el primer issue que es el registro de cuentas con sus condicionantes

2023-10-17 06:02 UTC, EmmanEsp requested changes
Bueno creo que con esto tienes para entretenerte, no puedes avanzar al siguiente issue si no sale este PR primero.

Mejoraste muchisimo, la organización del codigo es buenisima, cada funcion solo tiene codigo relacionado a lo que el nombre indica que hace.
Los nombres de las variables tambien mejoraron, son auto descriptivos, junto con los nombre de los metodos.

Siguie así panita.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +class Persona:
No hace falta abstraer al cliente en dos clases, con tener una sola es suficiente. Pasa por favor todas estas propiedades a la clase Cliente

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +import phonenumbers
Está bien que hayas usado esta librería, pero estaría mejor si las validaciones las haces tú checando la string.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +    #función para iniciar sesión con @staticmethod
¿Se te fue eliminar este comentario?

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +def validar_contraseña(contraseña):
No uses la "ñ" como nombre de nada, solamente la puedes usar dentro de string "ñ".

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +    if not re.search(r'[a-z]', contraseña):
Los regex usados de esta manera si me gustan, well played.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +    else:
No hace falta este else, lo puedes remover.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        else:
No es necesario esto:
```
else:
     continue
```
Si `validar_nombre(nombre_cliente)` retorna `False`, de todas maneras volverá a iniciar el ciclo.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        print("Ingresa uno o dos nombres, separados por espacio.")
No limites el numero de nombres a dos, por ejemplo, mi carnal tiene 3 nombres.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +    else:
¿Podrías quitar este else junto con el print? es algo que no tienen los otros metodos validadores, entonces hay que mantener uniformidad con el resto del codigo.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        else:
Este else no es necesario. Quitalo y ajusta nada mas el print de abajo a la identación correcta.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        else:
Lo mismo de arriba, este else no es necesario.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        else:
Este else tampoco es necesario

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        else:
Este else tampoco es necesario, hazlo mismo que en el primer comentario, con todos estos.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        cliente_existente = next((cliente for cliente in clientes_registrados if cliente.num_cel == mi_cliente.num_cel or cliente.email == mi_cliente.email), None)
Estaría mejor si esta linea la divieras en varias, esta un poco complicada de leer, lo mejor sería no hacer lineas tan largas.

2023-10-17 06:02 UTC, EmmanEsp commented on main.py
> +        num_celular = validar_telefono(num_celular_cl)
Aquí podrías hacer lo que estas haciendo en las otras validaciones, meter el metodo que valida dentro del if:
```
if validar_telefono(num_celular_cl):
     ......
```

2023-10-17 06:07 UTC, EmmanEsp commented
Para el siguiente PR intenta ponerle un titulo que tenga que ver con el issue que se esta resolviendo.

2023-10-17 21:48 UTC, Aziderius commented on main.py
> +import phonenumbers
a que libreria te refieres exactamente? a Phonenumbers?

2023-10-17 21:51 UTC, Aziderius commented on main.py
> +    #función para iniciar sesión con @staticmethod
No, como al inicio de comenzar a codear hice un diagrama de lo que necesitaba el código para funcionar, empecé a plasmar comentarios en donde a mi parecer necesitaba funciones y demás cosas. Entonces ese comentario fue para recordarme que ahí iba una función en el futuro para darle la capacidad al usuario de poder iniciar sesión

2023-11-03 02:48 UTC, EmmanEsp approved these changes

2023-11-17 23:21 UTC, EmmanEsp requested changes
agrega __pycache__ al git ignore

2023-11-21 21:42 UTC, merged